lib/alibaba_web/router.ex
defmodule AlibabaWeb.Router do
  use AlibabaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AlibabaWeb do
    pipe_through :browser
    get "/sitemap.xml", SitemapsController, :pages
    get "/blog", PageController, :blog
    get "/", PageController, :index
    get "/about", PageController, :about
    get "/contact", PageController, :contact
    get "/bikes", PageController, :bikes
    get "/steering", PageController, :steering
    get "/consult", PageController, :consult
    get "/activities", PageController, :activities
    resources "/posts", PostController
    get "/google93b50586b1832de5.html", PageController, :google
  end

  scope "/limlax2w3b3svt7m5g4a", AlibabaWeb do
    pipe_through :browser
    resources "/events", EventController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/recurring_event", Recurring_EventController
  end

  scope "/rktvcocdaki4m5o60sgb", AlibabaWeb do
    pipe_through :browser
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/directory", AlibabaWeb.Directory, as: :api do
    pipe_through :api
    resources "/events", EventController, only: [:index]
  end

end
#limlax2w3b3svt7m5g4a

lib/alibaba_web/templates/page/about.html.eex
<div class="hello">
    <h3 class="is-size-4 has-text-black">About Us</h3>
    <div class="ma-3">
      <p>Community Tracks Inverclyde will establish an active travel hub within Inverclyde, supporting and encouraging local people to make more journeys by bike or by foot.   Community Tracks Inverclyde is a project hosted by Inverclyde Community Development Trust jointly funded by The Climate Challenge Fund, part of Keep Scotland Beautiful, and by Smarter Places Smarter Choices in association with Paths for All and Inverclyde Council.</p>
      <p>Broadly, the project aims are to:</p>
      <ul>
        <li>Reduce waste/Reduce CO2 emission&#39;s</li>
        <li>Develop skills</li>
        <li>Promote social inclusion</li>
        <li>Enhance Employability through developing skills</li>
      </ul>
      <br>
      <p>These objectives will be achieved by:</p>
      <ul  >
        <li>Recycling bikes from landfill into the community</li>
        <li>Teaching cycle maintenance classes including educational and industry recognised qualifications</li>
        <li>Fix-your-own-bike workshops</li>
        <li>Cycle training and riding confidence sessions</li>
        <li>Cycle tours and guided rides within the local area and community</li>
      </ul>
    </div>
    <p><a href="https://www.dropbox.com/sh/ik9w6yaz0lywj7q/AAD73b9vQgfG7iLDgTdaVdlga?dl=0" target="_blank">Please click here for photos, logos and a summary of the project to download</a></p>
    <div class="columns">
      <div class="column">
      <br>
    <h3 class="is-size-5 has-text-black">Steering Groups</h3>
          <p class="is-size-6 has-text-black ">Steering Group Aims</p>
          <p>• To provide a forum for the local community and local organisations to be involved in the project, so the community continues to have the ownership of the project and to ensure the activities being delivered are in line with the needs of the community.<br/> • To bring input from national cycling organisations into a community setting and keep the project informed about best practices and successful strategies learned from other areas and projects.</p>
          <p class="is-size-6 has-text-black ">Current steering group organisations</p>
          <ul>
            <li>Inverclyde Council</li>
            <li>Inverclyde Community Development Trust</li>
            <li>Cycling UK</li>
            <li>Belles on Bikes Inverclyde</li>
            <li>Cycle Activity Bikes</li>
            <li>Canny Cycling</li>
            <li>Clyde Muirsheil Regional Park</li>
            <li>Police Scotland</li>
          </ul>
          <br/>
           <p class="is-size-6 has-text-black ">Approved steering group meeting minutes</p>
          <ul>
            <li><a href="https://s3.eu-west-2.amazonaws.com/comtracks/Community+Tracks+Inverclyde+steering+group+meeting+1+11.7.2017.pdf" target="_blank">11th July 2017</a></li>
            <li><a href="https://s3.eu-west-2.amazonaws.com/comtracks/Community+Tracks+Inverclyde+Steering+Group+minutes+22.8.2017+-+website.docx.pdf" target="_blank">22nd August 2017</a></li>
            <li><a href="https://s3.eu-west-2.amazonaws.com/comtracks/Inverclyde+Active+Travel++Steering+Group+Meeting+18.9.2017.pdf" target="_blank">18th September 2017</a></li>
          </ul>
          <br>
          <h3 class="is-size-5 has-text-black">  <a href="https://s3.eu-west-2.amazonaws.com/comtracks/Privacy+and+cookie+policy+template.pdf">Privacy and cookie policy</a></h3>

      </div>

      <div class="column">
          <img src="https://s3.eu-west-2.amazonaws.com/comtracks/photos/5004982_524e58a8.jpg" width="400px">
      </div>
    </div>
</div>

lib/alibaba_web/templates/page/activities.html.eex
<div id="calendar"></div>

lib/alibaba_web/templates/page/bikes.html.eex
      <div class="columns">
        <div class="column">
          <p>
            <h3 class="is-size-4 has-text-black">Bike Workshop</h3>
          </p>  
          <h3 class="is-size-5 has-text-black">Donate your old bikes</h3>
          <p>Do you have old bike you can donate to our project? Bike that are donated will be restored by volunteers and given to local schools for children who don’t have bikes themselves.</p>
          <a href="/contact">Please get in touch if you can donate a bike</a>
        </div>
        <div class="column ">
          <img src="/images/bikes.jpg" />
        </div>
     </div>

 

lib/alibaba_web/templates/page/blog.html.eex
<h2>Listing Posts</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for post <- @posts do %>
    <tr>
      <td><%= post.title %></td>
      <td><%= raw post.body %></td>

    </tr>
<% end %>
  </tbody>
</table>

lib/alibaba_web/templates/page/consult.html.eex
Consultation

lib/alibaba_web/templates/page/contact.html.eex
<div id="contact"></div>

lib/alibaba_web/templates/page/google.html.eex
google-site-verification: google93b50586b1832de5.html

lib/alibaba_web/templates/page/index.html.eex
<div class="columns is-marginless ">
  <div class="column  is-3 is-marginless is-paddingless">
    <nav class="panel "style="padding-left: 10px;padding-bottom: 10px">
      <p class="panel-heading has-text-weight-bold has-background-white">
        News
      </p>
      <%= for post <- @posts do %>

          <%= link post.title, to: post_path(@conn, :show, post), class: " panel-block"  %>

      <% end %>
      <a class="twitter-timeline" data-height="239" href="https://twitter.com/CTInverclyde?ref_src=twsrc%5Etfw">Tweets by CTInverclyde</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </nav>
  </div>
  <div class="column  is-marginless is-fullwidth">
    <div id="app"></div>
  </div>
</div>

lib/alibaba_web/templates/page/posts.html.eex
<h2>Listing Posts</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for post <- @posts do %>
    <tr>
      <td><%= post.title %></td>
      <td><%= raw post.body %></td>

    </tr>
<% end %>
  </tbody>
</table>

lib/alibaba_web/templates/page/steering.html.eex
Steering Group