lib/alibaba_web/router.ex
defmodule AlibabaWeb.Router do
  use AlibabaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AlibabaWeb do
    pipe_through :browser
    get "/sitemap.xml", SitemapsController, :pages
    get "/blog", PageController, :blog
    get "/", PageController, :index
    get "/about", PageController, :about
    get "/contact", PageController, :contact
    get "/bikes", PageController, :bikes
    get "/steering", PageController, :steering
    get "/consult", PageController, :consult
    get "/activities", PageController, :activities
    resources "/posts", PostController
    get "/google93b50586b1832de5.html", PageController, :google
  end

  scope "/limlax2w3b3svt7m5g4a", AlibabaWeb do
    pipe_through :browser
    resources "/events", EventController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/recurring_event", Recurring_EventController
  end

  scope "/rktvcocdaki4m5o60sgb", AlibabaWeb do
    pipe_through :browser
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/directory", AlibabaWeb.Directory, as: :api do
    pipe_through :api
    resources "/events", EventController, only: [:index]
  end

end
#limlax2w3b3svt7m5g4a

lib/alibaba_web/views/layout_view.ex
defmodule AlibabaWeb.LayoutView do
  use AlibabaWeb, :view

  
end

lib/alibaba_web/templates/layout/activities.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Community Tracks Inverclyde - Active Track, Walking & Cycling</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700|Material+Icons' rel="stylesheet"></link>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
        <!-- Global site tag (gtag.js) - Google Analytics -->

    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-106870652-1', 'auto');
      ga('set', 'anonymizeIP', true);
      ga('send', 'pageview');
    </script>

  </head>

  <body>
    <div class="container is-fluid">

      <div id="header"></div>

      <div class="is-fullwidth">

          <main role="main">
            <%= render @view_module, @view_template, assigns %>
          </main>

      </div>

      <div id="footer"></div>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
  </body>
</html>

lib/alibaba_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Welcome to Phauxth - an extensible authentication library for Elixir web apps</title>
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700|Material+Icons' rel="stylesheet"></link>
    <link rel="stylesheet" href="https://unpkg.com/buefy/lib/buefy.min.css" ></link>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script src="https://cdn.ckeditor.com/ckeditor5/11.0.1/classic/ckeditor.js"></script>


  </head>

  <body>

  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
            <%= if @current_user do %>
            <a class="navbar-item" href="<%= user_path(@conn, :show, @current_user.id) %>"><%= @current_user.email %></a>
          

            <%= link "Logout", to: session_path(@conn, :delete, @current_user), method: :delete %>
            <% else %>

            <% end %>

    </div>
  </nav>

    <section class="hero is-fullheight">
      <div class="hero-body">
        <div class="container has-text-centered">
          <div class="column is-4 is-offset-4">

            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

            <main role="main">
              <%= render @view_module, @view_template, assigns %>
            </main>
        </div>
      </div>
    </div> <!-- /container -->
    </section>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/alibaba_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Community Tracks Inverclyde - Active Track, Walking & Cycling</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700|Material+Icons' rel="stylesheet"></link>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
    <script>
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.12';
        fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-106870652-1', 'auto');
    ga('set', 'anonymizeIP', true);
    ga('send', 'pageview');
    </script>


  </head>

  <body>
    <div id="header"></div>
    <div class="container is-fluid">

      <div class="columns ">
        <div class="column is-9">
          <main role="main">
            <%= render @view_module, @view_template, assigns %>
          </main>
        </div>
          <div class="column is-3 ">
            <div id="fb-root"></div>
              <div class="fb-page" data-href="https://www.facebook.com/CommunityTracksInverclyde/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false">
                <blockquote cite="https://www.facebook.com/CommunityTracksInverclyde/" class="fb-xfbml-parse-ignore">
                  <a href="https://www.facebook.com/CommunityTracksInverclyde/" target='_top'>Community Tracks Inverclyde</a>
                </blockquote>
              </div>
            </div>
      </div>

      <div id="footer"></div>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
  </body>
</html>

lib/alibaba_web/templates/layout/blank.html.eex
  <%= render @view_module, @view_template, assigns %>

lib/alibaba_web/templates/layout/event.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Community Tracks - Admin</title>
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700|Material+Icons' rel="stylesheet"></link>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>

  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-start">
      <a class="navbar-item" href="/posts">
        News
      </a>
      <a class="navbar-item" href="/limlax2w3b3svt7m5g4a/events">
        Events
      </a>

    </div>

      <div class="navbar-end"
            <%= if @current_user do %>
            <a class="navbar-item" href="<%= user_path(@conn, :show, @current_user.id) %>"><%= @current_user.email %></a>
            <%= link "Logout", to: session_path(@conn, :delete, @current_user), method: :delete %>
            <% else %>

            <% end %>
      </div>
  </nav>


      </div>
    </div>


            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

            <main role="main">
              <%= render @view_module, @view_template, assigns %>
            </main>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/alibaba_web/templates/layout/home.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Community Tracks Inverclyde - Active Track, Walking & Cycling</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700|Material+Icons' rel="stylesheet"></link>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>


    <script>
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.12';
        fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-106870652-1', 'auto');
    ga('set', 'anonymizeIP', true);
    ga('send', 'pageview');
    </script>

  </head>

  <body>
    <div id="header"></div>

    <div class="container is-fluid ">

      <div class="columns is-centered is-marginless is-paddingless">

        <div class="column is-9 is-marginless is-paddingless">
          <main role="main">
            <%= render @view_module, @view_template, assigns %>
          </main>
        </div>

        <div class="column is-marginless is-paddingless  ">
          <div class="is-hidden-touch ">


              <iframe  src="https://www.youtube.com/embed/-vPTwtetbsA" frameborder="0" width="340" allow="autoplay; encrypted-media" allowfullscreen></iframe>
              <div id="fb-root"></div>
              <div class="fb-page" data-href="https://www.facebook.com/CommunityTracksInverclyde/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false" data-height="340">
                <blockquote cite="https://www.facebook.com/CommunityTracksInverclyde/" class="fb-xfbml-parse-ignore">
                  <a href="https://www.facebook.com/CommunityTracksInverclyde/" target='_top'>Community Tracks Inverclyde</a>
                </blockquote>
              </div>
          </div>
          <div class="is-hidden-desktop">


            <div id="fb-root"></div>
              <div class="fb-page" data-href="https://www.facebook.com/CommunityTracksInverclyde/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false">
                <blockquote cite="https://www.facebook.com/CommunityTracksInverclyde/" class="fb-xfbml-parse-ignore">
                  <a href="https://www.facebook.com/CommunityTracksInverclyde/" target='_top'>Community Tracks Inverclyde</a>
                </blockquote>
              </div>
          </div>
        </div>
      </div>
      <br/>
      <div id="activities"></div>
      <div id="footer"></div>


    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
  </body>
</html>